### ISSUE TITLE
Question About balanced Loss

### ISSUE THREAD

**Issue by eric-tc** [richardaecn/class-balanced-loss#6]
Hi,

thanks for sharing the code and for your great work. I have a question about the loss in your paper why you add +1 in (1) formula exactly `(1-p)(En-1+1).` Where does it came from? is the initial expected value? 

Thanks

**Comment by richardaecn** [comment]
Hi @eric-tc ,

In Figure 2, the volume of gray shaded region is E_{n-1}. After we sampled a new data, there are 2 possibilities showed in the right side of Figure 2: 
1) with probability p = E_{n-1}/N, the newly sampled data is inside the gray region, so the new volume is unchanged (E_{n-1}); 
2) with probability 1-p, the newly sampled data is outside the gray region, so the new volume is added by 1 (E_{n-1} + 1);

Therefore, the expected new volume is Equation 1.

**Comment by eric-tc** [comment]
Hi @richardaecn ,
thanks now it is clear.
